export default {
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  SESSION_FETCHING: 'SESSION_FETCHING',

  URLS_FETCHING: 'URLS_FETCHING',
  URLS_CANCEL: 'URLS_CANCEL',
  URLS_COMPLETE: 'URLS_COMPLETE',

  URL_SUBMITTING: 'URL_SUBMITTING',
  URL_SUBMISSION_COMPLETE: 'URL_SUBMISSION_COMPLETE',

  ADD_URL: 'ADD_URL',

  MODIFY_URL: 'MODIFY_URL',
  MODIFY_URL_COMPLETE: 'MODIFY_URL_COMPLETE'
}
